"""add partner name filter to uploader objects

Revision ID: 0a047d5c76ce
Revises: c78139c85781
Create Date: 2020-03-25 17:41:46.408234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a047d5c76ce'
down_revision = 'c78139c85781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploader_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_filter', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploader_objects', schema=None) as batch_op:
        batch_op.drop_column('partner_filter')

    # ### end Alembic commands ###
