"""add UploaderRelation model

Revision ID: 0ddec028ded2
Revises: 0a047d5c76ce
Create Date: 2020-03-26 05:17:36.564091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddec028ded2'
down_revision = '0a047d5c76ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploader_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_objects_id', sa.Integer(), nullable=True),
    sa.Column('impacted_column_name', sa.Text(), nullable=True),
    sa.Column('relation_constant', sa.Text(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_objects_id'], ['uploader_objects.id'], name=op.f('fk_uploader_relations_uploader_objects_id_uploader_objects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploader_relations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploader_relations')
    # ### end Alembic commands ###
