"""added dashboard model

Revision ID: 0e44544935eb
Revises: 548a950f20fb
Create Date: 2020-09-23 07:43:43.011950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e44544935eb'
down_revision = '548a950f20fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chart_type', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_dashboard_processor_id_processor')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_dashboard_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard')
    # ### end Alembic commands ###
