"""processor analysis added

Revision ID: 0fffff1de9f6
Revises: 1e28c02b430e
Create Date: 2020-07-20 14:36:11.430204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fffff1de9f6'
down_revision = '1e28c02b430e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('parameter', sa.Text(), nullable=True),
    sa.Column('parameter_2', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_processor_analysis_processor_id_processor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processor_analysis'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processor_analysis')
    # ### end Alembic commands ###
