"""additional plan metrics

Revision ID: 11f5dbfe1ec8
Revises: 0cb1458648f1
Create Date: 2024-03-20 05:43:34.840557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f5dbfe1ec8'
down_revision = '0cb1458648f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpm', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cpc', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cplpv', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cpbc', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cpv', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cpcv', sa.Numeric(), nullable=True))

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digital_agency_fees', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('trad_agency_fees', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('dcm_service_fees', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('dcm_service_fees')
        batch_op.drop_column('trad_agency_fees')
        batch_op.drop_column('digital_agency_fees')

    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.drop_column('cpcv')
        batch_op.drop_column('cpv')
        batch_op.drop_column('cpbc')
        batch_op.drop_column('cplpv')
        batch_op.drop_column('cpc')
        batch_op.drop_column('cpm')

    # ### end Alembic commands ###
