"""added campaign product client

Revision ID: 12e31aa8b227
Revises: ca5c15f90f79
Create Date: 2019-07-28 04:15:32.281383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e31aa8b227'
down_revision = 'ca5c15f90f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_processor_campaign_id_campaign'), 'campaign', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_processor_campaign_id_campaign'), type_='foreignkey')
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
