"""initial models for tutorials

Revision ID: 137dd17bd9a9
Revises: 445c315176e6
Create Date: 2021-08-10 14:04:43.340153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137dd17bd9a9'
down_revision = '445c315176e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutorial'))
    )
    op.create_table('tutorial_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=True),
    sa.Column('tutorial_level', sa.Integer(), nullable=True),
    sa.Column('header', sa.Text(), nullable=True),
    sa.Column('sub_header', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('alert', sa.Text(), nullable=True),
    sa.Column('alert_level', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], name=op.f('fk_tutorial_stage_tutorial_id_tutorial')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutorial_stage'))
    )
    op.create_table('user_tutorial',
    sa.Column('tutorial_stage_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_stage_id'], ['tutorial_stage.id'], name=op.f('fk_user_tutorial_tutorial_stage_id_tutorial_stage')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_tutorial_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tutorial')
    op.drop_table('tutorial_stage')
    op.drop_table('tutorial')
    # ### end Alembic commands ###
