"""additional dash columns

Revision ID: 157be46e7c75
Revises: f5aa6645c62b
Create Date: 2024-01-10 14:12:35.773011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157be46e7c75'
down_revision = 'f5aa6645c62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('tab')

    # ### end Alembic commands ###
