"""update account filter col to text

Revision ID: 161dac15d8a1
Revises: d912d8e83dc9
Create Date: 2022-12-12 14:47:12.663595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161dac15d8a1'
down_revision = 'd912d8e83dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor_datasources', schema=None) as batch_op:
        batch_op.alter_column('account_filter',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor_datasources', schema=None) as batch_op:
        batch_op.alter_column('account_filter',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
