"""add campaign_id to project

Revision ID: 19bf5cd06469
Revises: 20746f8abdd2
Create Date: 2023-10-11 15:26:55.820153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bf5cd06469'
down_revision = '20746f8abdd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_project_campaign_id_campaign'), 'campaign', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_campaign_id_campaign'), type_='foreignkey')
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
