"""add notes

Revision ID: 19e42e2eb58d
Revises: 7f7f6321adda
Create Date: 2021-06-21 20:55:11.437317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e42e2eb58d'
down_revision = '7f7f6321adda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('notification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_notes_processor_id_processor')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notes_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_note_id_notes'), 'notes', ['note_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_note_id_notes'), type_='foreignkey')
        batch_op.drop_column('note_id')

    op.drop_table('notes')
    # ### end Alembic commands ###
