"""change ProcessorDataSources vendor_key type to text

Revision ID: 1acc3d61103c
Revises: f110ec38a393
Create Date: 2023-07-23 15:10:20.201094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acc3d61103c'
down_revision = 'f110ec38a393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor_datasources', schema=None) as batch_op:
        batch_op.alter_column('vendor_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor_datasources', schema=None) as batch_op:
        batch_op.alter_column('vendor_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
