"""add duplication type to uploader_objects

Revision ID: 1e28c02b430e
Revises: df823bf9bcfd
Create Date: 2020-05-01 12:20:39.790763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e28c02b430e'
down_revision = 'df823bf9bcfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploader_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplication_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploader_objects', schema=None) as batch_op:
        batch_op.drop_column('duplication_type')

    # ### end Alembic commands ###
