"""add title to contacts

Revision ID: 231fb780259e
Revises: e149b8c63a5c
Create Date: 2023-10-05 11:07:05.212879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231fb780259e'
down_revision = 'e149b8c63a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('contact_title')

    # ### end Alembic commands ###
