"""add note_type and header

Revision ID: 3a8656dd4ec7
Revises: 735217c877f5
Create Date: 2023-03-22 17:15:24.975651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8656dd4ec7'
down_revision = '735217c877f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('note_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('note_type')
        batch_op.drop_column('header')

    # ### end Alembic commands ###
