"""add brandtracker

Revision ID: 3f65f3507252
Revises: 1acc3d61103c
Create Date: 2023-08-10 13:19:39.434836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f65f3507252'
down_revision = '1acc3d61103c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brandtracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('primary_date', sa.Date(), nullable=True),
    sa.Column('comparison_date', sa.Date(), nullable=True),
    sa.Column('titles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_brandtracker_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brandtracker'))
    )
    with op.batch_alter_table('brandtracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brandtracker_name'), ['name'], unique=False)

    op.create_table('brandtracker_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=True),
    sa.Column('brandtracker_id', sa.Integer(), nullable=True),
    sa.Column('metric_column', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['brandtracker_id'], ['brandtracker.id'], name=op.f('fk_brandtracker_dimensions_brandtracker_id_brandtracker')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brandtracker_dimensions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brandtracker_dimensions')
    with op.batch_alter_table('brandtracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brandtracker_name'))

    op.drop_table('brandtracker')
    # ### end Alembic commands ###
