"""add rates

Revision ID: 41f8a7f531f7
Revises: c46817910e3a
Create Date: 2020-01-12 18:40:12.133426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f8a7f531f7'
down_revision = 'c46817910e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.Text(), nullable=True),
    sa.Column('adserving_fee', sa.Numeric(), nullable=True),
    sa.Column('reporting_fee', sa.Numeric(), nullable=True),
    sa.Column('rate_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_card.id'], name=op.f('fk_rates_rate_card_id_rate_card')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rates'))
    )
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_processor_rate_card_id_rate_card'), 'rate_card', ['rate_card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_processor_rate_card_id_rate_card'), type_='foreignkey')
        batch_op.drop_column('rate_card_id')

    op.drop_table('rates')
    # ### end Alembic commands ###
