"""add campaign/client/product

Revision ID: 422d57bbaa42
Revises: ca5c15f90f79
Create Date: 2019-07-27 08:27:09.229360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422d57bbaa42'
down_revision = 'ca5c15f90f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_product_client_id_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)

    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_campaign_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign'))
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_name'), ['name'], unique=False)

    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_processor_campaign_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_processor_campaign_id_campaign'), 'campaign', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_processor_campaign_id_campaign'), type_='foreignkey')
        batch_op.create_foreign_key('fk_processor_campaign_id_user', 'user', ['campaign_id'], ['id'])

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_name'))

    op.drop_table('campaign')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))

    op.drop_table('product')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_name'))

    op.drop_table('client')
    # ### end Alembic commands ###
