"""fix notification day for notes

Revision ID: 445c315176e6
Revises: 19e42e2eb58d
Create Date: 2021-06-22 10:40:35.696259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445c315176e6'
down_revision = '19e42e2eb58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_day', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('notification_day')

    # ### end Alembic commands ###
