"""add RequestLog

Revision ID: 50146fa3b6f9
Revises: 54b753ecac38
Create Date: 2024-02-23 18:16:57.981929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50146fa3b6f9'
down_revision = '54b753ecac38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_request_log_plan_id_plan')),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_request_log_processor_id_processor')),
    sa.ForeignKeyConstraint(['uploader_id'], ['uploader.id'], name=op.f('fk_request_log_uploader_id_uploader')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_request_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_log'))
    )
    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_log_timestamp'))

    op.drop_table('request_log')
    # ### end Alembic commands ###
