"""added dashboard filters model

Revision ID: 5104473f174a
Revises: 56256faf209a
Create Date: 2020-10-27 15:01:29.475466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5104473f174a'
down_revision = '56256faf209a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.Column('filter_col', sa.Text(), nullable=True),
    sa.Column('filter_val', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], name=op.f('fk_dashboard_filter_dashboard_id_dashboard')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_filter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_filter')
    # ### end Alembic commands ###
