"""add in requests for processor

Revision ID: 51b6e978e09e
Revises: 8e96e5364b0e
Create Date: 2020-02-04 16:37:13.689880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b6e978e09e'
down_revision = '8e96e5364b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('fix_type', sa.String(length=128), nullable=True),
    sa.Column('column_name', sa.Text(), nullable=True),
    sa.Column('wrong_value', sa.Text(), nullable=True),
    sa.Column('correct_value', sa.Text(), nullable=True),
    sa.Column('filter_column_name', sa.Text(), nullable=True),
    sa.Column('filter_column_value', sa.Text(), nullable=True),
    sa.Column('fix_description', sa.Text(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fixed_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_requests_processor_id_processor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_fix_type'), ['fix_type'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_request_id_requests'), 'requests', ['request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_request_id_requests'), type_='foreignkey')
        batch_op.drop_column('request_id')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_fix_type'))

    op.drop_table('requests')
    # ### end Alembic commands ###
