"""add contact table

Revision ID: 53d5fea556d8
Revises: 60d336e5a059
Create Date: 2023-09-11 14:51:25.652451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d5fea556d8'
down_revision = '60d336e5a059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_submitted', sa.Date(), nullable=True),
    sa.Column('partner_name', sa.Text(), nullable=True),
    sa.Column('sales_representative', sa.Text(), nullable=True),
    sa.Column('phone1', sa.Text(), nullable=True),
    sa.Column('email_address1', sa.Text(), nullable=True),
    sa.Column('am_traffic_contact', sa.Text(), nullable=True),
    sa.Column('phone2', sa.Text(), nullable=True),
    sa.Column('email_address2', sa.Text(), nullable=True),
    sa.Column('director', sa.Text(), nullable=True),
    sa.Column('associate_media_director', sa.Text(), nullable=True),
    sa.Column('supervisor', sa.Text(), nullable=True),
    sa.Column('associate_strategist', sa.Text(), nullable=True),
    sa.Column('rfp_file_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_contacts_partner_id_partner')),
    sa.ForeignKeyConstraint(['rfp_file_id'], ['rfp_file.id'], name=op.f('fk_contacts_rfp_file_id_rfp_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
