"""add insertion_order table

Revision ID: 54b753ecac38
Revises: c37084efc016
Create Date: 2024-02-20 18:55:39.842085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b753ecac38'
down_revision = 'c37084efc016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insertion_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('insertion_order', sa.String(), nullable=True),
    sa.Column('project_number', sa.Integer(), nullable=True),
    sa.Column('document_date', sa.String(), nullable=True),
    sa.Column('billing_contact', sa.String(), nullable=True),
    sa.Column('attn', sa.String(), nullable=True),
    sa.Column('media_representative', sa.String(), nullable=True),
    sa.Column('publisher_contact', sa.String(), nullable=True),
    sa.Column('publisher_contact_email', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('agency_contact', sa.String(), nullable=True),
    sa.Column('agency_contact_email', sa.String(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_insertion_order_partner_id_partner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insertion_order'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insertion_order')
    # ### end Alembic commands ###
