"""added creation time to dashboard model

Revision ID: 56256faf209a
Revises: 0e44544935eb
Create Date: 2020-09-23 08:34:08.987204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56256faf209a'
down_revision = '0e44544935eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
