"""add walkthrough models

Revision ID: 59c31df47970
Revises: 6444251d6dd2
Create Date: 2021-11-02 07:35:25.332879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c31df47970'
down_revision = '6444251d6dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkthrough',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edit_name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_walkthrough'))
    )
    op.create_table('walkthrough_slide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('walkthrough_id', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('slide_text', sa.Text(), nullable=True),
    sa.Column('show_me_element', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthrough.id'], name=op.f('fk_walkthrough_slide_walkthrough_id_walkthrough')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_walkthrough_slide'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walkthrough_slide')
    op.drop_table('walkthrough')
    # ### end Alembic commands ###
