"""add report_builder

Revision ID: 5bbf6bbf6c38
Revises: ca596dd6dc2f
Create Date: 2023-06-08 13:52:29.304647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbf6bbf6c38'
down_revision = 'ca596dd6dc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('report_name', sa.String(length=128), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_processor_reports_processor_id_processor')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_processor_reports_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processor_reports'))
    )
    with op.batch_alter_table('processor_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processor_reports_report_name'), ['report_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processor_reports_report_name'))

    op.drop_table('processor_reports')
    # ### end Alembic commands ###
