"""add specs model

Revision ID: 60d336e5a059
Revises: beefba65fb1f
Create Date: 2023-09-06 17:09:08.230853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d336e5a059'
down_revision = 'beefba65fb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Text(), nullable=True),
    sa.Column('partner', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Text(), nullable=True),
    sa.Column('key_art_direction', sa.Text(), nullable=True),
    sa.Column('messaging', sa.Text(), nullable=True),
    sa.Column('weight', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('phase_cta', sa.Text(), nullable=True),
    sa.Column('loops_animation', sa.Text(), nullable=True),
    sa.Column('aspect_ratio', sa.Text(), nullable=True),
    sa.Column('video_length', sa.Text(), nullable=True),
    sa.Column('file_formats', sa.Text(), nullable=True),
    sa.Column('max_video_size_mb', sa.Text(), nullable=True),
    sa.Column('optimal_video_load_size_mb', sa.Text(), nullable=True),
    sa.Column('frame_rate', sa.Text(), nullable=True),
    sa.Column('bitrate', sa.Text(), nullable=True),
    sa.Column('hd_sd', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rfp_file_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_specs_partner_id_partner')),
    sa.ForeignKeyConstraint(['rfp_file_id'], ['rfp_file.id'], name=op.f('fk_specs_rfp_file_id_rfp_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specs')
    # ### end Alembic commands ###
