"""followers

Revision ID: 620de9f6bb5a
Revises: ee00425e7b2c
Create Date: 2019-07-02 16:10:55.061532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620de9f6bb5a'
down_revision = 'ee00425e7b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
