"""add tableau datasource to processor

Revision ID: 6444251d6dd2
Revises: 24ab337f83c4
Create Date: 2021-09-01 11:10:39.301712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6444251d6dd2'
down_revision = '24ab337f83c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tableau_datasource', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.drop_column('tableau_datasource')

    # ### end Alembic commands ###
