"""notes tag update

Revision ID: 6c0b2bbe83f9
Revises: 161dac15d8a1
Create Date: 2023-02-07 18:05:38.579921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0b2bbe83f9'
down_revision = '161dac15d8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('environment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kpi', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('kpi')
        batch_op.drop_column('environment')
        batch_op.drop_column('country')
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###
