"""add dimensions and data to notes

Revision ID: 735217c877f5
Revises: 2eb17a922705
Create Date: 2023-02-28 14:16:32.390727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735217c877f5'
down_revision = '2eb17a922705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimensions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('dimensions')

    # ### end Alembic commands ###
