"""added projects to models

Revision ID: 7f7f6321adda
Revises: 5016ce19958d
Create Date: 2021-04-25 21:32:56.979818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7f6321adda'
down_revision = '5016ce19958d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_number_max',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_number_max'))
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_number', sa.Text(), nullable=True),
    sa.Column('initial_project_number', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('media', sa.Boolean(), nullable=True),
    sa.Column('creative', sa.Boolean(), nullable=True),
    sa.Column('date_opened', sa.Date(), nullable=True),
    sa.Column('flight_start_date', sa.Date(), nullable=True),
    sa.Column('flight_end_date', sa.Date(), nullable=True),
    sa.Column('exhibit', sa.Text(), nullable=True),
    sa.Column('sow_received', sa.Text(), nullable=True),
    sa.Column('billing_dates', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_project_client_id_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('project_number_processor',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_project_number_processor_processor_id_processor')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_number_processor_project_id_project'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_number_processor')
    op.drop_table('project')
    op.drop_table('project_number_max')
    # ### end Alembic commands ###
