"""processor imports

Revision ID: 819155a85124
Revises: 17a7a0f1fa83
Create Date: 2019-08-20 15:12:11.604204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819155a85124'
down_revision = '17a7a0f1fa83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('account_filter', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('api_fields', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_processor_imports_processor_id_processor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processor_imports'))
    )
    with op.batch_alter_table('processor_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processor_imports_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processor_imports_name'))

    op.drop_table('processor_imports')
    # ### end Alembic commands ###
