"""add html response to chat

Revision ID: 832129d46d71
Revises: 1d916b5dbd68
Create Date: 2023-05-02 16:43:47.937493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832129d46d71'
down_revision = '1d916b5dbd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('html_response')

    # ### end Alembic commands ###
