"""added PlanPhase

Revision ID: 86a27b1c6e43
Revises: 42d4a8e06afd
Create Date: 2022-05-11 14:25:38.983800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a27b1c6e43'
down_revision = '42d4a8e06afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_phase_plan_id_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_phase'))
    )
    with op.batch_alter_table('plan_phase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_phase_name'), ['name'], unique=False)

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_phase_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_partner_plan_id_plan', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_partner_plan_phase_id_plan_phase'), 'plan_phase', ['plan_phase_id'], ['id'])
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_partner_plan_phase_id_plan_phase'), type_='foreignkey')
        batch_op.create_foreign_key('fk_partner_plan_id_plan', 'plan', ['plan_id'], ['id'])
        batch_op.drop_column('plan_phase_id')

    with op.batch_alter_table('plan_phase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_phase_name'))

    op.drop_table('plan_phase')
    # ### end Alembic commands ###
