"""add challenges

Revision ID: 8970421390f4
Revises: 50b54e3b0d33
Create Date: 2024-07-18 09:47:36.675092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8970421390f4'
down_revision = '50b54e3b0d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge'))
    )
    op.create_table('user_challenge',
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_user_challenge_challenge_id_challenge')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_challenge_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_challenge')
    op.drop_table('challenge')
    # ### end Alembic commands ###
