"""fix conversion_type on conversion

Revision ID: 8e7c6cd1187a
Revises: 3bff23082cc4
Create Date: 2020-01-13 18:41:52.678794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7c6cd1187a'
down_revision = '3bff23082cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversion_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion', schema=None) as batch_op:
        batch_op.drop_column('conversion_type')

    # ### end Alembic commands ###
