"""processor tasks

Revision ID: 8ee5de53413f
Revises: a1c83af4eb7a
Create Date: 2019-07-14 18:06:06.940206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee5de53413f'
down_revision = 'a1c83af4eb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('processor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'processor', ['processor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'processor_id')
    # ### end Alembic commands ###
