"""add url to notes

Revision ID: 902bc3484b66
Revises: 5bbf6bbf6c38
Create Date: 2023-06-29 12:01:33.014219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902bc3484b66'
down_revision = '5bbf6bbf6c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
