"""add sow

Revision ID: a57ff98200e5
Revises: 86a27b1c6e43
Create Date: 2022-05-31 12:04:46.714996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57ff98200e5'
down_revision = '86a27b1c6e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('project_contact', sa.String(), nullable=True),
    sa.Column('date_submitted', sa.Date(), nullable=True),
    sa.Column('liquid_contact', sa.String(), nullable=True),
    sa.Column('liquid_project', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('campaign', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('total_project_budget', sa.Numeric(), nullable=True),
    sa.Column('ad_serving', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_sow_plan_id_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sow'))
    )
    with op.batch_alter_table('sow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sow_project_name'), ['project_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sow_project_name'))

    op.drop_table('sow')
    # ### end Alembic commands ###
