"""add questions to tutorial stage model

Revision ID: a64e3b680f0c
Revises: 137dd17bd9a9
Create Date: 2021-08-11 11:53:03.963706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64e3b680f0c'
down_revision = '137dd17bd9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question_answers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial_stage', schema=None) as batch_op:
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('question_answers')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
