"""scheduler

Revision ID: a7391737d041
Revises: d971ca5451ec
Create Date: 2019-10-17 15:26:09.320656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7391737d041'
down_revision = 'd971ca5451ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_scheduler',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_task_scheduler_processor_id_processor')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_scheduler_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_scheduler'))
    )
    with op.batch_alter_table('task_scheduler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_scheduler_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_scheduler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_scheduler_name'))

    op.drop_table('task_scheduler')
    # ### end Alembic commands ###
