"""initial uploader model

Revision ID: b588896794ab
Revises: a7391737d041
Create Date: 2019-11-30 18:01:11.507729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b588896794ab'
down_revision = 'a7391737d041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_uploader_campaign_id_campaign')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_uploader_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploader'))
    )
    with op.batch_alter_table('uploader', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploader_name'), ['name'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_uploader_id_uploader'), 'uploader', ['uploader_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_task_uploader_id_uploader'), 'uploader', ['uploader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_uploader_id_uploader'), type_='foreignkey')
        batch_op.drop_column('uploader_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_uploader_id_uploader'), type_='foreignkey')
        batch_op.drop_column('uploader_id')

    with op.batch_alter_table('uploader', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploader_name'))

    op.drop_table('uploader')
    # ### end Alembic commands ###
