"""processor

Revision ID: c1e6aa4ca4bc
Revises: 8e31d0ff69f3
Create Date: 2019-07-13 17:51:05.029082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e6aa4ca4bc'
down_revision = '8e31d0ff69f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('last_run_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processor_created_at'), 'processor', ['created_at'], unique=False)
    op.create_index(op.f('ix_processor_last_run_time'), 'processor', ['last_run_time'], unique=False)
    op.create_index(op.f('ix_processor_name'), 'processor', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processor_name'), table_name='processor')
    op.drop_index(op.f('ix_processor_last_run_time'), table_name='processor')
    op.drop_index(op.f('ix_processor_created_at'), table_name='processor')
    op.drop_table('processor')
    # ### end Alembic commands ###
