"""additional indexes

Revision ID: c37084efc016
Revises: f3ab0d7296c2
Create Date: 2024-02-13 20:28:01.816423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37084efc016'
down_revision = 'f3ab0d7296c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processor_analysis_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_processor_analysis_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_processor_analysis_parameter'), ['parameter'], unique=False)
        batch_op.create_index(batch_op.f('ix_processor_analysis_processor_id'), ['processor_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_processor_id'), ['processor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_processor_id'))

    with op.batch_alter_table('processor_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processor_analysis_processor_id'))
        batch_op.drop_index(batch_op.f('ix_processor_analysis_parameter'))
        batch_op.drop_index(batch_op.f('ix_processor_analysis_key'))
        batch_op.drop_index(batch_op.f('ix_processor_analysis_date'))

    # ### end Alembic commands ###
