"""added uploader objects

Revision ID: c78139c85781
Revises: 51b6e978e09e
Create Date: 2020-03-21 15:20:27.235715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78139c85781'
down_revision = '51b6e978e09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploader_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('uploader_type', sa.Text(), nullable=True),
    sa.Column('object_level', sa.Text(), nullable=True),
    sa.Column('name_create_type', sa.Text(), nullable=True),
    sa.Column('media_plan_columns', sa.Text(), nullable=True),
    sa.Column('spend_type', sa.Text(), nullable=True),
    sa.Column('spend_value', sa.Numeric(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['uploader.id'], name=op.f('fk_uploader_objects_uploader_id_uploader')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploader_objects'))
    )
    with op.batch_alter_table('uploader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fb_account_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_plan', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploader', schema=None) as batch_op:
        batch_op.drop_column('media_plan')
        batch_op.drop_column('fb_account_id')

    op.drop_table('uploader_objects')
    # ### end Alembic commands ###
