"""additional columns in plan

Revision ID: ca596dd6dc2f
Revises: f71017fd69a4
Create Date: 2023-06-01 11:34:33.710976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca596dd6dc2f'
down_revision = 'f71017fd69a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('targeting_bucket', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('creative_line_item', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('copy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retailer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('buy_model', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('buy_rate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('serving', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ad_rate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reporting_rate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kpi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_type_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_fee_rate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verification_rate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reporting_source', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ad_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('placement_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('package_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_channel', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.drop_column('media_channel')
        batch_op.drop_column('package_description')
        batch_op.drop_column('placement_description')
        batch_op.drop_column('ad_type')
        batch_op.drop_column('size')
        batch_op.drop_column('reporting_source')
        batch_op.drop_column('verification_rate')
        batch_op.drop_column('service_fee_rate')
        batch_op.drop_column('data_type_1')
        batch_op.drop_column('kpi')
        batch_op.drop_column('reporting_rate')
        batch_op.drop_column('ad_rate')
        batch_op.drop_column('serving')
        batch_op.drop_column('buy_rate')
        batch_op.drop_column('buy_model')
        batch_op.drop_column('retailer')
        batch_op.drop_column('copy')
        batch_op.drop_column('creative_line_item')
        batch_op.drop_column('targeting_bucket')
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
