"""added processor

Revision ID: ca5c15f90f79
Revises: 8e31d0ff69f3
Create Date: 2019-07-17 14:53:14.999468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5c15f90f79'
down_revision = '8e31d0ff69f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('tableau_workbook', sa.Text(), nullable=True),
    sa.Column('tableau_view', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processor_name'), ['name'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'processor', ['processor_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'processor', ['processor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('processor_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('processor_id')

    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processor_name'))

    op.drop_table('processor')
    # ### end Alembic commands ###
