"""add to plan rules and placements

Revision ID: cb243d4cd1bf
Revises: 832129d46d71
Create Date: 2023-05-30 16:04:09.536001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb243d4cd1bf'
down_revision = '832129d46d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('environment', sa.Text(), nullable=True))

    with op.batch_alter_table('plan_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('place_col', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_plan_rule_plan_id_plan'), 'plan', ['plan_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_plan_rule_partner_id_partner'), 'partner', ['partner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_rule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_plan_rule_partner_id_partner'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_plan_rule_plan_id_plan'), type_='foreignkey')
        batch_op.drop_column('place_col')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.drop_column('environment')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
