"""add additional metrics to partner

Revision ID: d912d8e83dc9
Revises: f71cfc755aab
Create Date: 2022-09-12 16:47:35.529064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd912d8e83dc9'
down_revision = 'f71cfc755aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cplpv', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cpbc', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cpv', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cpcv', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('cpcv')
        batch_op.drop_column('cpv')
        batch_op.drop_column('cpbc')
        batch_op.drop_column('cplpv')

    # ### end Alembic commands ###
