"""change processor imports to datasources

Revision ID: d971ca5451ec
Revises: 819155a85124
Create Date: 2019-09-11 14:12:50.387664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd971ca5451ec'
down_revision = '819155a85124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor_datasources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('account_filter', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('api_fields', sa.String(length=128), nullable=True),
    sa.Column('vendor_key', sa.String(length=128), nullable=True),
    sa.Column('full_placement_columns', sa.Text(), nullable=True),
    sa.Column('placement_columns', sa.Text(), nullable=True),
    sa.Column('auto_dictionary_placement', sa.Text(), nullable=True),
    sa.Column('auto_dictionary_order', sa.Text(), nullable=True),
    sa.Column('active_metrics', sa.Text(), nullable=True),
    sa.Column('vm_rules', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name=op.f('fk_processor_datasources_processor_id_processor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processor_datasources'))
    )
    with op.batch_alter_table('processor_datasources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processor_datasources_name'), ['name'], unique=False)

    with op.batch_alter_table('processor_imports', schema=None) as batch_op:
        batch_op.drop_index('ix_processor_imports_name')

    op.drop_table('processor_imports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor_imports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('processor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('account_filter', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('api_fields', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], name='fk_processor_imports_processor_id_processor'),
    sa.PrimaryKeyConstraint('id', name='pk_processor_imports')
    )
    with op.batch_alter_table('processor_imports', schema=None) as batch_op:
        batch_op.create_index('ix_processor_imports_name', ['name'], unique=False)

    with op.batch_alter_table('processor_datasources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processor_datasources_name'))

    op.drop_table('processor_datasources')
    # ### end Alembic commands ###
