"""add dcm category to conversions

Revision ID: dc928299dedf
Revises: 8e7c6cd1187a
Create Date: 2020-01-14 13:51:25.886405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc928299dedf'
down_revision = '8e7c6cd1187a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dcm_category', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion', schema=None) as batch_op:
        batch_op.drop_column('dcm_category')

    # ### end Alembic commands ###
