"""added urnesolved relations

Revision ID: df823bf9bcfd
Revises: 0ddec028ded2
Create Date: 2020-04-30 08:40:00.934169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df823bf9bcfd'
down_revision = '0ddec028ded2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploader_relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unresolved_relations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploader_relations', schema=None) as batch_op:
        batch_op.drop_column('unresolved_relations')

    # ### end Alembic commands ###
