"""add project_id to tasks

Revision ID: e149b8c63a5c
Revises: 53d5fea556d8
Create Date: 2023-09-27 14:28:39.778909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e149b8c63a5c'
down_revision = '53d5fea556d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_task_project_id_project'), 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_project_id_project'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
