"""add total_time and created_at to Task

Revision ID: f3ab0d7296c2
Revises: 157be46e7c75
Create Date: 2024-02-13 16:31:46.566332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ab0d7296c2'
down_revision = '157be46e7c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_time', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_time')

    # ### end Alembic commands ###
