"""add PlanEffectiveness table

Revision ID: f5aa6645c62b
Revises: b2b764e574fc
Create Date: 2023-12-07 18:01:33.600344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5aa6645c62b'
down_revision = 'b2b764e574fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_effectiveness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor_name', sa.Text(), nullable=True),
    sa.Column('selected_val', sa.Float(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_effectiveness_plan_id_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_effectiveness'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_effectiveness')
    # ### end Alembic commands ###
