"""add total_budget to partnerplacements

Revision ID: f71017fd69a4
Revises: cb243d4cd1bf
Create Date: 2023-05-30 18:54:47.263949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71017fd69a4'
down_revision = 'cb243d4cd1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_budget', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_placements', schema=None) as batch_op:
        batch_op.drop_column('total_budget')

    # ### end Alembic commands ###
