"""add partner_type column

Revision ID: f71cfc755aab
Revises: a57ff98200e5
Create Date: 2022-08-05 14:08:15.781470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71cfc755aab'
down_revision = 'a57ff98200e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_type', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('partner_type')

    # ### end Alembic commands ###
