"""add additional fees to processor

Revision ID: fe38ee2a0a3b
Revises: 41f8a7f531f7
Create Date: 2020-01-13 11:26:54.863039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe38ee2a0a3b'
down_revision = '41f8a7f531f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dcm_service_fees', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('digital_agency_fees', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('trad_agency_fees', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processor', schema=None) as batch_op:
        batch_op.drop_column('trad_agency_fees')
        batch_op.drop_column('digital_agency_fees')
        batch_op.drop_column('dcm_service_fees')

    # ### end Alembic commands ###
